/**
 * Created by coolm on 7/4/2016.
 */

$(document).ready(function()
{
    $("button#Jan").click(function()
        {
            $("div#january").show();
            $("div#february").hide();
            $("div#march").hide();
            $("div#april").hide();
            $("div#may").hide();
            $("div#june").hide();
            $("div#july").hide();
            $("div#august").hide();
            $("div#september").hide();
            $("div#october").hide();
            $("div#november").hide();
            $("div#december").hide();
        }
    )

    $("button#Feb").click(function()
    {
        $("div#january").hide();
        $("div#february").show();
        $("div#march").hide();
        $("div#april").hide();
        $("div#may").hide();
        $("div#june").hide();
        $("div#july").hide();
        $("div#august").hide();
        $("div#september").hide();
        $("div#october").hide();
        $("div#november").hide();
        $("div#december").hide();
    }
    )

    $("button#Mac").click(function()
        {
            $("div#january").hide();
            $("div#february").hide();
            $("div#march").show();
            $("div#april").hide();
            $("div#may").hide();
            $("div#june").hide();
            $("div#july").hide();
            $("div#august").hide();
            $("div#september").hide();
            $("div#october").hide();
            $("div#november").hide();
            $("div#december").hide();
        }
    )

    $("button#Apr").click(function()
        {
            $("div#january").hide();
            $("div#february").hide();
            $("div#march").hide();
            $("div#april").show();
            $("div#may").hide();
            $("div#june").hide();
            $("div#july").hide();
            $("div#august").hide();
            $("div#september").hide();
            $("div#october").hide();
            $("div#november").hide();
            $("div#december").hide();
        }
    )

    $("button#May").click(function()
        {
            $("div#january").hide();
            $("div#february").hide();
            $("div#march").hide();
            $("div#april").hide();
            $("div#may").show();
            $("div#june").hide();
            $("div#july").hide();
            $("div#august").hide();
            $("div#september").hide();
            $("div#october").hide();
            $("div#november").hide();
            $("div#december").hide();
        }
    )

    $("button#Jun").click(function()
        {
            $("div#january").hide();
            $("div#february").hide();
            $("div#march").hide();
            $("div#april").hide();
            $("div#may").hide();
            $("div#june").show();
            $("div#july").hide();
            $("div#august").hide();
            $("div#september").hide();
            $("div#october").hide();
            $("div#november").hide();
            $("div#december").hide();
        }
    )

    $("button#Jul").click(function()
        {
            $("div#january").hide();
            $("div#february").hide();
            $("div#march").hide();
            $("div#april").hide();
            $("div#may").hide();
            $("div#june").hide();
            $("div#july").show();
            $("div#august").hide();
            $("div#september").hide();
            $("div#october").hide();
            $("div#november").hide();
            $("div#december").hide();
        }
    )

    $("button#Aug").click(function()
        {
            $("div#january").hide();
            $("div#february").hide();
            $("div#march").hide();
            $("div#april").hide();
            $("div#may").hide();
            $("div#june").hide();
            $("div#july").hide();
            $("div#august").show();
            $("div#september").hide();
            $("div#october").hide();
            $("div#november").hide();
            $("div#december").hide();
        }
    )

    $("button#Sep").click(function()
        {
            $("div#january").hide();
            $("div#february").hide();
            $("div#march").hide();
            $("div#april").hide();
            $("div#may").hide();
            $("div#june").hide();
            $("div#july").hide();
            $("div#august").hide();
            $("div#september").show();
            $("div#october").hide();
            $("div#november").hide();
            $("div#december").hide();
        }
    )

    $("button#Oct").click(function()
        {
            $("div#january").hide();
            $("div#february").hide();
            $("div#march").hide();
            $("div#april").hide();
            $("div#may").hide();
            $("div#june").hide();
            $("div#july").hide();
            $("div#august").hide();
            $("div#september").hide();
            $("div#october").show();
            $("div#november").hide();
            $("div#december").hide();
        }
    )

    $("button#Nov").click(function()
        {
            $("div#january").hide();
            $("div#february").hide();
            $("div#march").hide();
            $("div#april").hide();
            $("div#may").hide();
            $("div#june").hide();
            $("div#july").hide();
            $("div#august").hide();
            $("div#september").hide();
            $("div#october").hide();
            $("div#november").show();
            $("div#december").hide();
        }
    )

    $("button#Dec").click(function()
        {
            $("div#december").show();
            $("div#january").hide();
            $("div#february").hide();
            $("div#march").hide();
            $("div#april").hide();
            $("div#may").hide();
            $("div#june").hide();
            $("div#july").hide();
            $("div#august").hide();
            $("div#september").hide();
            $("div#october").hide();
            $("div#november").hide();
        }
    )

})
